sudo: false
language: python
python:
    - 2.7

install:
    - pip install pep8

script:
    - num_errors=`find . -name \*.py -exec pep8 --ignore=E501,E402 {} + | wc -l`
    - |
        if (( $num_errors > 0 )); then
          exit;
        fi
    - python setup.py test
