sudo: false
language: python
python:
    - 2.7

install:
    - pip install pyyaml
    - pip install Jinja2
    - pip install requests
    - pip install setuptools
    - pip install mock
    - pip install mockito
    - pip install gitpython

script:
    - export PATH=$PATH:/home/travis/build/seomoz/roger-mesos-tools/bin:/home/travis/build/seomoz/roger-mesos-tools/cli
    - python setup.py test
