sudo: false
language: python
python:
    - 2.7

install:
    - python setup.py install
    - pip install pytest==2.5.1
    - pip install mock==1.0.1
    - pip install mockito==0.5.2

git:
  submodules: false
