sudo: false
language: python
python:
    - 2.7

install:
    - python setup.py install
    - pip install pytest==3.0.5
    - pip install mock==1.0.1
    - pip install mockito==0.5.2

# The majority of these tests are setup properly under roger-promote. They're
# not working here, so silencing on this branch for now.
script: /bin/true

git:
  submodules: false
