sudo: false
language: python
python:
    - 2.7

install:
    - python setup.py install
    - pip install pytest==2.5.1
    - pip install mock==1.0.1
    - pip install mockito==0.5.2

script:
#    - num_errors=`find cli/ tests/ bin/ -name \*.py -exec pep8 --ignore=E501,E402 {} + | wc -l`
#    - |
#        if (( $num_errors > 0 )); then
#          exit 1;
#        fi
    - py.test -v tests 
